import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>betterkarts : Steal The Better Deal</title>
        <meta name="description" content="Generated by Gyanendra Yadav" />
        <link rel="shortcut icon" type="image/jpg" href="fav.png"/>
        
      </Head>
    
        <div className="container md:mx-10 ">
          <Image  width={1920} height={1080} src="/shopping8.png" alt="aisehi" />
        </div>

    
    </>
  )
}
